# Generated by Django 5.2.2 on 2025-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('subtext', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=255, null=True)),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=255, null=True)),
                ('icon_class', models.CharField(max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='logo_images/')),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_color', models.CharField(max_length=255, null=True)),
                ('font_size', models.CharField(max_length=255, null=True)),
                ('font_weight', models.CharField(max_length=255, null=True)),
                ('font_style', models.CharField(max_length=255, null=True)),
                ('button_color', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
