from django.contrib import admin
from .models import *

admin.site.register(school_ict_herosection)
admin.site.register(school_aboutus)
admin.site.register(stats_spaeak_for_themsleves)
admin.site.register(dean_message)
admin.site.register(Departments_school)
admin.site.register(our_prorams)
admin.site.register(Faculty_of_ICt)
admin.site.register(Notices)
admin.site.register(Event_gallery)
admin.site.register(student_clubs_activities)
admin.site.register(Placement_stats)
admin.site.register(Recent_placement)
admin.site.register(Recruiterss)
admin.site.register(startup_stats)
admin.site.register(student_startup)
admin.site.register(Student_achievements)
admin.site.register(faculty_herosection)
admin.site.register(Departments_name)
admin.site.register(faculty_department_herosection)
admin.site.register(Faculty_profile)
admin.site.register(Board_studies)
admin.site.register(Laboratory_Excellence)
admin.site.register(conference_activity)
admin.site.register(department_hod_message)
admin.site.register(department_statistics)
admin.site.register(Academic_programs_department)
admin.site.register(Curriculum_department)
admin.site.register(Research_excellence_departments)
admin.site.register(Research_excellence_departments_projects)
admin.site.register(Research_excellence_departments_stats)
admin.site.register(Studnet_achievers_department)
admin.site.register(Our_achievements_departemnts)
admin.site.register(Ctaegory_lab)
admin.site.register(Specialization)
admin.site.register(Expertise_skills_student_achiever)
