# Generated by Django 5.2.2 on 2025-07-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyDirectory', '0002_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='award_achievements_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='award_achievements_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='award_recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('Institutional', models.BooleanField(default=False)),
                ('University', models.BooleanField(default=False)),
                ('International', models.BooleanField(default=False)),
                ('Professional', models.BooleanField(default=False)),
                ('Nattional', models.BooleanField(default=False)),
                ('Department', models.BooleanField(default=False)),
                ('Governmnet', models.BooleanField(default=False)),
                ('Academic', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Awards_timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, choices=[('University', 'University'), ('Institutional', 'Institutional'), ('National', 'National')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='community_initiative_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Community Outreach', 'Coomunity Outreach'), ('Environmnental Conservation', 'Environmenta Conservation'), ('Education Access', 'Education Access'), ('Cybersecurtiy Awareness', 'Cybersecurty Awareness'), ('Healthcare Support', 'Healthcare Support'), ('Technology For Good', 'Technollogy For Good')], max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficairies', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('photos', models.CharField(blank=True, max_length=255, null=True)),
                ('key_impact', models.TextField(null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invited_talks_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invited_talks_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notatble_achievements_award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_journals', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patent_filing_timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Filed', 'Filed'), ('Under Examination', 'Under Examination'), ('Published', 'Published')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patent_portfolio_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patent_portfolio_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_certifications_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_certifications_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Development_certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('FDP', 'FDP'), ('Conference', 'Conference')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='publication_satistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skilss_Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_imapcat_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_impact_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='social_impact_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_contributons', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaking_engagements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_people', models.CharField(blank=True, max_length=255, null=True)),
                ('slides_available', models.BooleanField(default=False)),
                ('recording_available', models.BooleanField(default=False)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='speaking_expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_talks', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('text_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='name',
            new_name='button1_text',
        ),
        migrations.AddField(
            model_name='publications',
            name='button1_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='button2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='button2_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='citations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='grade',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('A', 'A'), ('A+', 'A+')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='type_of_publication',
            field=models.CharField(blank=True, choices=[('Journal', 'Journal'), ('Conference', 'Conference')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Patent_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('application_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_field', models.CharField(blank=True, max_length=255, null=True)),
                ('patent_office', models.CharField(blank=True, max_length=255, null=True)),
                ('filed_on', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Filed', 'Filed'), ('Under Examination', 'Under Examination'), ('Published', 'Published')], max_length=255, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('inventors', models.ManyToManyField(related_name='inventos', to='facultyDirectory.facultydirectory')),
            ],
        ),
        migrations.CreateModel(
            name='Certification_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('comapany_name', models.CharField(blank=True, max_length=255, null=True)),
                ('obtained_year', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, choices=[('Associate', 'Associate'), ('Professional', 'Professional'), ('Specialiaton', 'Specialization')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Not Verified', 'Not Verified')], max_length=255, null=True)),
                ('skills_covered', models.ManyToManyField(related_name='skilss', to='facultyDirectory.skilss_certifications')),
            ],
        ),
    ]
