# Generated by Django 5.2.2 on 2025-07-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyDirectory', '0016_alter_community_initiative_social_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_initiative_social',
            name='category',
            field=models.CharField(blank=True, choices=[('Community Outreach', 'Coomunity Outreach'), ('Environmnental Conservation', 'Environmenta Conservation'), ('Education Access', 'Education Access'), ('Cybersecurtiy Awareness', 'Cybersecurty Awareness'), ('Healthcare Support', 'Healthcare Support'), ('Technology For Good', 'Technollogy For Good')], max_length=255, null=True),
        ),
    ]
