# Generated by Django 5.2.2 on 2025-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coe_heroection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='funded_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='funded_project_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255)),
                ('school_tag', models.CharField(help_text='engeineering or biotechnology', max_length=255)),
                ('card_description', models.TextField()),
                ('principal', models.CharField(max_length=255)),
                ('funding_agency', models.CharField(max_length=255)),
                ('amount', models.CharField(help_text='45.2 lakhs', max_length=255)),
                ('duration', models.CharField(help_text='3 years(2022-2025)', max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='funded_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(help_text='e.g., 20+', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class if needed', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(help_text='e.g., 20+', max_length=100)),
                ('title', models.CharField(help_text='e.g., Research Centers', max_length=100)),
                ('color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class if needed', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='join_startups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('values', models.CharField(help_text='e.g 1 , 2 ,3', max_length=100)),
                ('stats_title', models.CharField(max_length=100)),
                ('stats_description', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='research publicatons or patents', max_length=255)),
                ('card_title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('journals', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('Type', models.CharField(max_length=255)),
                ('impact_factor', models.DecimalField(decimal_places=5, max_digits=5)),
                ('citations', models.PositiveIntegerField()),
                ('scopus_id', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('issn_ibbn', models.CharField(max_length=255)),
                ('indexing', models.CharField(max_length=255)),
                ('quartile', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='publications_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(help_text='e.g., 20+', max_length=100)),
                ('title', models.CharField(help_text='e.g., Research Centers', max_length=100)),
                ('color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class if needed', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('established_year', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('facilities', models.CharField(max_length=255)),
                ('research_areas', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='labs/')),
                ('button1_text', models.CharField(max_length=255)),
                ('button2_text', models.CharField(max_length=255)),
                ('url1', models.URLField()),
                ('url2', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Startups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('card_title', models.CharField()),
                ('card_description', models.TextField()),
                ('card_icon', models.CharField(max_length=200)),
                ('background_color', models.CharField(max_length=255)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='startupimg/')),
            ],
        ),
        migrations.CreateModel(
            name='Startups_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(help_text='e.g., 20+', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class if needed', max_length=50, null=True)),
            ],
        ),
    ]
