# Generated by Django 5.2.2 on 2025-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Researchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_techonologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funded_project_card',
            name='school_tag',
        ),
        migrations.RemoveField(
            model_name='researchlab',
            name='description',
        ),
        migrations.RemoveField(
            model_name='researchlab',
            name='technologies',
        ),
        migrations.AddField(
            model_name='funded_project',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funded_project_card',
            name='school',
            field=models.CharField(blank=True, choices=[('Biotechnology', 'Biotechnology'), ('Buddhist Studies and Civilization', 'Buddhist Studies and Civilization'), ('Engineering', 'Engineering'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Information and Communication Technology', 'Information and Communication Technology'), ('Humanitites and Social Sciences', 'Humanitites and Social Sciences'), ('Law, justice and Governanance', 'Law, justice and Governanance'), ('Management', 'Management'), ('Vocational Studies and Applied Sciences', 'Vocational Studies and Applied Sciences')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='school',
            field=models.CharField(blank=True, choices=[('Biotechnology', 'Biotechnology'), ('Buddhist Studies and Civilization', 'Buddhist Studies and Civilization'), ('Engineering', 'Engineering'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Information and Communication Technology', 'Information and Communication Technology'), ('Humanitites and Social Sciences', 'Humanitites and Social Sciences'), ('Law, justice and Governanance', 'Law, justice and Governanance'), ('Management', 'Management'), ('Vocational Studies and Applied Sciences', 'Vocational Studies and Applied Sciences')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications_herosection',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publications_herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
        migrations.AlterField(
            model_name='coe_heroection',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coe_heroection',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coe_heroection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='funded_project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='card_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='category',
            field=models.CharField(blank=True, choices=[('Climate Research', 'Climate Research'), ('Biotechnology', 'Biotechnology'), ('Energy Systems', 'Energy Systems')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_project_card',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_stats',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_stats',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_stats',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funded_stats',
            name='values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='Type',
            field=models.CharField(blank=True, choices=[('Article', 'Article'), ('Thesis', 'Thesis'), ('Review', 'Review'), ('Conderence Paper', 'Conference Paper'), ('Book Chapter', 'Book Chapter'), ('Book', 'Book'), ('Book Review', 'Book Review'), ('Letter', 'Letter'), ('News Clippings', 'News Clippings'), ('Editoriial', 'Editorial')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='category',
            field=models.CharField(blank=True, choices=[('Research Publications', 'Research Publications'), ('Patents', 'Patents')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='indexing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='issn_ibbn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='journals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='quartile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications_herosection',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publications_herosection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchhighlight',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchhighlight',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchhighlight',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchhighlight',
            name='values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='button2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='facilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='head',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='researchlab',
            name='research_areas',
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='school',
            field=models.CharField(blank=True, choices=[('Biotechnology', 'Biotechnology'), ('Buddhist Studies and Civilization', 'Buddhist Studies and Civilization'), ('Engineering', 'Engineering'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Information and Communication Technology', 'Information and Communication Technology'), ('Humanitites and Social Sciences', 'Humanitites and Social Sciences'), ('Law, justice and Governanance', 'Law, justice and Governanance'), ('Management', 'Management'), ('Vocational Studies and Applied Sciences', 'Vocational Studies and Applied Sciences')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='url1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='url2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchlab',
            name='research_areas',
            field=models.ManyToManyField(to='Researchapp.research_techonologies'),
        ),
    ]
