# Generated by Django 5.2.2 on 2025-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Researchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='impact_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
