# Generated by Django 5.2.2 on 2025-06-24 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='Target URL or file download link')),
                ('icon_class', models.CharField(blank=True, help_text="CSS class for button icon, e.g., 'fa fa-download'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='admission_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sub_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionTab_international',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('anchor_id', models.CharField(help_text='HTML ID for scrolling', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStep_international',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactOffice_ainternationaldmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(choices=[('admissions', 'International Admissions Office'), ('services', 'Student Services')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('working_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='courses_coursesoffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_category', models.CharField(help_text='undergraduate or postgraduate', max_length=255)),
                ('card_title', models.CharField(max_length=255)),
                ('specialisation', models.CharField(max_length=255)),
                ('seats', models.PositiveIntegerField(max_length=255)),
                ('year', models.PositiveIntegerField(max_length=255)),
                ('eligibility', models.CharField(max_length=255)),
                ('Highlights', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses_offered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eligibility_rservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notice_title', models.CharField(max_length=255, null=True)),
                ('notice_description', models.TextField(null=True)),
                ('notice_backgroundcolor', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRequirement_interanational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PhD', 'Doctoral')], max_length=5)),
                ('academic_requirement', models.TextField()),
                ('english_proficiency', models.TextField()),
                ('additional_requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fee_policy', models.TextField()),
                ('icon_feepolicy', models.CharField(max_length=255, null=True)),
                ('color_fee', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure_internationaladdmisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PhD', 'Doctoral')], max_length=5)),
                ('tuition_fee_min', models.IntegerField()),
                ('tuition_fee_max', models.IntegerField()),
                ('accommodation_min', models.IntegerField()),
                ('accommodation_max', models.IntegerField()),
                ('living_expenses_min', models.IntegerField()),
                ('living_expenses_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('icon_class', models.CharField(default='fa fa-calendar', help_text="CSS class for icon, e.g., 'fa fa-calendar-check'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='international_admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program_Feestructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('yearly_fee', models.PositiveIntegerField(help_text='Total fee per year (INR)')),
                ('total_fee', models.PositiveIntegerField(help_text='Total fee for entire duration (INR)')),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('hostel_fee', models.PositiveIntegerField(default=0)),
                ('mess_fee', models.PositiveIntegerField(default=0)),
                ('other_fee', models.PositiveIntegerField(default=0)),
                ('scholarship_info', models.CharField(blank=True, help_text="e.g., 'Merit-based scholarships available'", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='programs_eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='elegibility criteria or reservation policy', max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('academic_qualification', models.TextField()),
                ('entrance_exam', models.CharField(max_length=200)),
                ('age_limit', models.CharField(help_text="Example: 'Born on or after October 1, 1999' or 'No age limit'", max_length=100)),
                ('general_eligibility_percent', models.DecimalField(decimal_places=2, help_text='General category minimum percentage', max_digits=5)),
                ('reserved_eligibility_percent', models.DecimalField(decimal_places=2, help_text='Reserved category minimum percentage', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ready_to_apply_coussesoffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
                ('button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('icon_class', models.CharField(default='fa fa-check-circle', help_text="CSS class for icon, e.g., 'fa fa-id-card'", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship_international',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='schools_coursesoffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_images/')),
            ],
        ),
        migrations.CreateModel(
            name='stats_coursesoffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(help_text='e.g., 20+', max_length=100)),
                ('title', models.CharField(help_text='e.g., Schools, programs', max_length=100)),
                ('color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class if needed', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stats_international',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(help_text='e.g., 20+', max_length=100)),
                ('title', models.CharField(help_text='e.g., Schools, programs', max_length=100)),
                ('color', models.CharField(help_text="Hex or Tailwind color name, e.g., 'blue', 'green'", max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional: icon class if needed', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='step_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(max_length=255)),
                ('step_description', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('icon_clas', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(help_text='current or upcoming', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSupportService_international',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument_international',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('eligibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissionapp.eligibilityrequirement_interanational')),
            ],
        ),
    ]
