# Generated by Django 5.2.2 on 2025-07-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission_process_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_offered_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eligibility_rservation_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_description', models.TextField(null=True)),
                ('notice_backgroundcolor', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_Payments_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_structure_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Fee structre or Payment optionsor Scholoardhips', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='international_admissions_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prospectus_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('sie', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionapp.fee_structure_section')),
            ],
        ),
        migrations.CreateModel(
            name='Ready_toAplly_internationaladmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship_feee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('elegibility', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionapp.fee_structure_section')),
            ],
        ),
        migrations.CreateModel(
            name='School_course_offered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='admission_process',
        ),
        migrations.DeleteModel(
            name='Courses_offered',
        ),
        migrations.DeleteModel(
            name='eligibility_rservation',
        ),
        migrations.DeleteModel(
            name='international_admissions',
        ),
        migrations.RemoveField(
            model_name='actionbutton',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='ready_to_apply_coussesoffered',
            name='button_url',
        ),
        migrations.AddField(
            model_name='actionbutton',
            name='button_text2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionbutton',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='prospectu/'),
        ),
        migrations.AddField(
            model_name='applicationstep_international',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee_structure',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ready_to_apply_coussesoffered',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scholarship_international',
            name='fee_wavler',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actionbutton',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actionbutton',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admissiontab_international',
            name='anchor_id',
            field=models.CharField(help_text='HTML ID for scrolling', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissiontab_international',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstep_international',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationstep_international',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstep_international',
            name='step_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationstep_international',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactoffice_ainternationaldmissions',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactoffice_ainternationaldmissions',
            name='office_type',
            field=models.CharField(choices=[('international admissions', 'International Admissions Office'), ('student services', 'Student Services')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactoffice_ainternationaldmissions',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactoffice_ainternationaldmissions',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='Highlights',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='eligibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='graduate_category',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Doctoral', 'Doctoral')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='specialisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courses_coursesoffered',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityrequirement_interanational',
            name='academic_requirement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityrequirement_interanational',
            name='english_proficiency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_structure',
            name='color_fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fee_structure',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_structure',
            name='fee_policy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fee_structure',
            name='icon_feepolicy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fee_structure',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure_internationaladdmisions',
            name='accommodation_max',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure_internationaladdmisions',
            name='accommodation_min',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure_internationaladdmisions',
            name='living_expenses_max',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure_internationaladdmisions',
            name='living_expenses_min',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure_internationaladdmisions',
            name='tuition_fee_max',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure_internationaladdmisions',
            name='tuition_fee_min',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='event_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=255),
        ),
        migrations.AlterField(
            model_name='programs_eligibility',
            name='academic_qualification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programs_eligibility',
            name='age_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programs_eligibility',
            name='general_eligibility_percent',
            field=models.CharField(blank=True, help_text='General category minimum percentage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programs_eligibility',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programs_eligibility',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programs_eligibility',
            name='reserved_eligibility_percent',
            field=models.CharField(blank=True, help_text='Reserved category minimum percentage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ready_to_apply_coussesoffered',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ready_to_apply_coussesoffered',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ready_to_apply_coussesoffered',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ready_to_apply_coussesoffered',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requireddocument_international',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship_international',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship_international',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats_international',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats_international',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats_international',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats_international',
            name='values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='step_process',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='step_process',
            name='icon_clas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='step_process',
            name='status',
            field=models.CharField(blank=True, choices=[('Completd', 'Completed'), ('Upcoming', 'Upcoming')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='step_process',
            name='step_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='step_process',
            name='step_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentsupportservice_international',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentsupportservice_international',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee_payments_option',
            name='section_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissionapp.fee_structure_section'),
        ),
        migrations.AddField(
            model_name='program_feestructure',
            name='section_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admissionapp.fee_structure_section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses_coursesoffered',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admissionapp.school_course_offered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schools_coursesoffered',
            name='course',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='admissionapp.school_course_offered'),
            preserve_default=False,
        ),
    ]
