# Generated by Django 5.2.2 on 2025-06-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
