# Generated by Django 5.2.2 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_schedule_regulatioons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(null=True, upload_to='schedule/')),
            ],
        ),
        migrations.CreateModel(
            name='academicherosection_Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='acdemic_regulations_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='benefits_cbcbs_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cbcs_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='centre_of_excellence_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='centre_of_excellence_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coe_gallery_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='explore_academic_excellence_schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Schools/')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_directory_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='faculty_background/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultydirectory_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='institutional_reports_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mous_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='school_journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='school_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='technology_schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='what_is_cbcs_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('card_title', models.CharField(blank=True, max_length=255, null=True)),
                ('card_desc', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='academicherosection',
        ),
        migrations.DeleteModel(
            name='cbcs_courses',
        ),
        migrations.DeleteModel(
            name='Facultydirectory',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='benefits_cbcbs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='benefits_cbcbs',
            name='title',
        ),
        migrations.RemoveField(
            model_name='centerofexcellence',
            name='description',
        ),
        migrations.RemoveField(
            model_name='centerofexcellence',
            name='title',
        ),
        migrations.RemoveField(
            model_name='coe_gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coe_gallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='collaborationprogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collaborationprogram',
            name='title',
        ),
        migrations.RemoveField(
            model_name='faculty_join',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='herosection_cbcs',
            name='credits_coount',
        ),
        migrations.RemoveField(
            model_name='herosection_cbcs',
            name='elective_courses',
        ),
        migrations.RemoveField(
            model_name='herosection_cbcs',
            name='flexebility',
        ),
        migrations.RemoveField(
            model_name='herosection_cbcs',
            name='grading_scale',
        ),
        migrations.RemoveField(
            model_name='herosection_cbcs',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='herosection_cbcs',
            name='icon_text',
        ),
        migrations.RemoveField(
            model_name='herosection_centereofexcellence',
            name='ResearchAndstudents',
        ),
        migrations.RemoveField(
            model_name='herosection_centereofexcellence',
            name='coe_count',
        ),
        migrations.RemoveField(
            model_name='herosection_centereofexcellence',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='herosection_centereofexcellence',
            name='icon_text',
        ),
        migrations.RemoveField(
            model_name='herosection_centereofexcellence',
            name='memberrs_count',
        ),
        migrations.RemoveField(
            model_name='herosection_centereofexcellence',
            name='projects_count',
        ),
        migrations.RemoveField(
            model_name='herosection_mou',
            name='activemou_count',
        ),
        migrations.RemoveField(
            model_name='herosection_mou',
            name='countries_count',
        ),
        migrations.RemoveField(
            model_name='herosection_mou',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='herosection_mou',
            name='icon_text',
        ),
        migrations.RemoveField(
            model_name='herosection_mou',
            name='participants_counts',
        ),
        migrations.RemoveField(
            model_name='herosection_mou',
            name='publications_count',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='accreditation_count',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='acheivements_counts',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='icon_text',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='reprts_count',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='sub_description',
        ),
        migrations.RemoveField(
            model_name='herosection_reports',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='institutionalreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='institutionalreport',
            name='title',
        ),
        migrations.RemoveField(
            model_name='partnerinstitute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnerinstitute',
            name='title',
        ),
        migrations.RemoveField(
            model_name='upcomingopportunity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='upcomingopportunity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='what_is_cbcs',
            name='card_desc',
        ),
        migrations.RemoveField(
            model_name='what_is_cbcs',
            name='card_title',
        ),
        migrations.RemoveField(
            model_name='what_is_cbcs',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='academicregulation',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerofexcellence',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerofexcellence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coe/'),
        ),
        migrations.AddField(
            model_name='institutionalreport',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionalreport',
            name='button1_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionalreport',
            name='view_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upcomingopportunity',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='button2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='url1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academic_stayupdated',
            name='url2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='category',
            field=models.CharField(choices=[('admission', 'Admission'), ('exam', 'Examination'), ('break', 'Break'), ('holiday', 'Holiday'), ('academic', 'Academic')], max_length=250),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], max_length=250),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicregulation',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academicregulation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='academicregulation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='benefits_cbcbs',
            name='card_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='benefits_cbcbs',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbcs_gradingscale',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbcs_gradingscale',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbcs_gradingscale',
            name='percentage_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbcs_gradingscale',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cbcs_gradingscale',
            name='status',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbcs_gradingscale',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='card_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='faculty_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='project_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centerofexcellence',
            name='student_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coe_gallery',
            name='card_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collaborationprogram',
            name='benefits',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collaborationprogram',
            name='card_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collaborationprogram',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationprogram',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationprogram',
            name='participants',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='button2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='url1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborations_mou',
            name='url2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='explore_cbcs',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='explore_cbcs',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='explore_cbcs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='explore_cbcs',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='explore_cbcs',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_join',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_join',
            name='button2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_join',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_join',
            name='url1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_join',
            name='url2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='department',
            field=models.CharField(blank=True, choices=[('School of Information and Communication Technology', 'School of Information and Communication Technology'), ('School of Biotechnology', 'School of Biotechnology'), ('School of Engineering', 'School of Engineering'), ('School of Management', 'School of Management'), ('School of Humanities', 'School of Humanities'), ('School of Law', 'School of Law')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='experience_years',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='faculty_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/'),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='specialization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='herosection_cbcs',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_cbcs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='herosection_cbcs',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_centereofexcellence',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_centereofexcellence',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='herosection_centereofexcellence',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_mou',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_mou',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_reports',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosection_reports',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='herosection_reports',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='card_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='category',
            field=models.CharField(choices=[('institutional', 'Institutional'), ('accreditation', 'Accreditation'), ('finance', 'Finance'), ('student', 'Student')], max_length=250),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='downloads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='file_size_mb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='institutionalreport',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='join_coe',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='join_coe',
            name='button2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='join_coe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='join_coe',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='join_coe',
            name='url1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='join_coe',
            name='url2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinstitute',
            name='card_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partnerinstitute',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinstitute',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinstitute',
            name='since_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinstitute',
            name='types',
            field=models.CharField(choices=[('Academic MOU', 'Academic MOU'), ('Research MOU', 'Research MOU')], max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerinstitute',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='benefits',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='elegibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingopportunity',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='what_is_cbcs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='what_is_cbcs',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='explore_academic_excellence_schools',
            name='technology',
            field=models.ManyToManyField(blank=True, null=True, to='academicapp.technology_schools'),
        ),
    ]
