# Generated by Django 5.2.2 on 2025-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_backgroundcolor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Career_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Personalized career counselling', max_length=200)),
                ('description', models.TextField()),
                ('points', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='esteemed_campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='internship_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('summer', 'Summer Internships'), ('industrial', 'Industrial Training'), ('research', 'Research Internships'), ('international', 'International Programs')], max_length=255, unique=20)),
                ('description', models.TextField()),
                ('durations', models.CharField(help_text='8-12 weeks', max_length=255)),
                ('stipened', models.CharField(max_length=255)),
                ('eligibility', models.CharField(choices=[('2nd_year', '2nd Year'), ('3rd_year', '3rd Year'), ('final_year', 'Final Year'), ('all_years', 'All Years'), ('top_performers', 'Top Performers')], max_length=255)),
                ('application_deadlne', models.CharField(help_text='March 31, 2024', max_length=255)),
                ('button1_text', models.CharField(help_text='Apply now', max_length=255)),
                ('button2_text', models.CharField(help_text='Learn More', max_length=255)),
                ('button1_url', models.URLField()),
                ('button2_url', models.URLField()),
                ('icon_backgroundcolor', models.CharField(max_length=255)),
                ('icon_clas', models.CharField(max_length=255)),
                ('company', models.ManyToManyField(blank=True, to='placementapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='internship_providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interns', models.PositiveIntegerField()),
                ('company', models.ManyToManyField(blank=True, to='placementapp.companies')),
            ],
        ),
        migrations.CreateModel(
            name='journey_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('button1_text', models.CharField(max_length=255)),
                ('button2_text', models.CharField(max_length=255)),
                ('button1_url', models.URLField()),
                ('button2_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='keytopics_traning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Quantitative aptitude', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='package_distributons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementOfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('Domestic', 'Domestic Placements'), ('International', 'International Offers')], max_length=20, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ready_enhanceskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button1_text', models.CharField(max_length=255)),
                ('button2_text', models.CharField(max_length=255)),
                ('button1_url', models.URLField()),
                ('button2_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hired_count', models.CharField(help_text="e.g. '32+', '25+'", max_length=10)),
                ('role_types', models.PositiveIntegerField(default=2)),
                ('active_since', models.PositiveIntegerField(default=2024)),
                ('sector', models.CharField(choices=[('IT & Tech', 'IT & Tech'), ('Core Engineering', 'Core Engineering'), ('Consulting & Finance', 'Consulting & Finance'), ('Government & Research', 'Government & Research')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='recuriments_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
                ('button1_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='training_career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UGPGPlacementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=20, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='upcoming_workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(help_text='December 12,2024', max_length=255)),
                ('duration', models.CharField(help_text='10:00 AM- 4:00PM', max_length=255)),
                ('faculty_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('All levels', 'All Levels')], max_length=255)),
                ('button1_text', models.CharField(max_length=255)),
                ('button1_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='What_inside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_color', models.CharField(max_length=255)),
                ('icon_clas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='what_recruiters_say',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photo/')),
            ],
        ),
        migrations.DeleteModel(
            name='InternshipStep',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
        migrations.DeleteModel(
            name='WhyChooseUsPoint',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
        migrations.RenameField(
            model_name='internshipopportunity',
            old_name='apply_link',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='placementstatistic',
            old_name='chart_data',
            new_name='chart_year',
        ),
        migrations.RenameField(
            model_name='placementstatistic',
            old_name='label',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='label',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='internshipopportunity',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='internshipopportunity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='internshipopportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='internshipopportunity',
            name='stipend',
        ),
        migrations.RemoveField(
            model_name='placementbrochure',
            name='year',
        ),
        migrations.AddField(
            model_name='brochuresectionitem',
            name='button_text',
            field=models.CharField(default=1, help_text='Download full brochure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochuresectionitem',
            name='button_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochuresectionitem',
            name='card_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochuresectionitem',
            name='card_title',
            field=models.CharField(default=1, help_text='Ready to expore?', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochuresectionitem',
            name='gradient_background',
            field=models.CharField(default=1, help_text="Enter a CSS gradient e.g., 'linear-gradient(to right, #ff7e5f, #feb47b)'", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brochuresectionitem',
            name='year',
            field=models.CharField(default=1, help_text='2024-2025', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipopportunity',
            name='button_text',
            field=models.CharField(default=1, help_text='apply for internship', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipopportunity',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementbrochure',
            name='description',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementstatistic',
            name='chart_sector',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementstatistic',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='duration',
            field=models.CharField(default=1, help_text='3 weeks', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='occurence',
            field=models.CharField(default=1, help_text='3x per week', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='key_topics',
            field=models.ManyToManyField(blank=True, to='placementapp.keytopics_traning'),
        ),
        migrations.AddField(
            model_name='internship_providers',
            name='tech',
            field=models.ManyToManyField(blank=True, to='placementapp.technologies'),
        ),
    ]
