# Generated by Django 5.2.2 on 2025-07-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0002_application_process_career_services_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='card_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='gradient_background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brochuresectionitem',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship_cards',
            name='button1_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship_cards',
            name='button2_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship_cards',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internshipopportunity',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internshipopportunity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internshipopportunity',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internshipopportunity',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='placementbrochure',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placementbrochure',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='what_inside',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='what_inside',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='what_inside',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='what_inside',
            name='icon_clas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
