# Generated by Django 5.2.2 on 2025-06-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium_number', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_seats', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('incharge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('incharge_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('peakseason_pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('off_peakseason_pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('half_day_pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('full_day_pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('your_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('available_slots', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_chart', models.FileField(blank=True, null=True, upload_to='ratechart/')),
                ('booking_rules', models.FileField(blank=True, null=True, upload_to='bookingrule/')),
                ('terms_conditions_file', models.FileField(blank=True, null=True, upload_to='termsandcondition/')),
                ('booking_guidelines', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_type', models.CharField(blank=True, choices=[('Auditoriums', 'Auditoriums'), ('Conference Rooms', 'Conference Rooms'), ('Accommodation', 'Accommodation'), ('Sports Facility', 'Sports Facility'), ('Kitchen and Dining', 'Kitchen and Dining')], max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, choices=[('50+ people', '50+ people'), ('100+ people', '100+ people'), ('200+ people', '200+ people'), ('300+ people', '300+ people')], max_length=255, null=True)),
                ('price_range', models.CharField(blank=True, choices=[('0-5000', '0-5000'), ('5000-10,000', '5000-10,000'), ('10,000-15,000', '10,000-15,000'), ('15,000+', '15,000+')], max_length=255, null=True)),
                ('season', models.CharField(blank=True, choices=[('Peak Season', 'Peak Season'), ('Off-Peak Season', 'Off-Peak Season')], max_length=255, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookingapp.userrole')),
            ],
        ),
    ]
