# Generated by Django 5.2.2 on 2025-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='aboutimg/')),
                ('button1_text', models.CharField(max_length=100)),
                ('button2_text', models.CharField(max_length=100)),
                ('button1_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
                ('button1_text', models.CharField(max_length=100, null=True)),
                ('button2_text', models.CharField(max_length=100, null=True)),
                ('button1_url', models.URLField(null=True)),
                ('button2_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campus_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campusimg/')),
                ('text', models.CharField(max_length=200)),
                ('button1_text', models.CharField(max_length=50)),
                ('button1_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus_life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='realtedimg/')),
                ('card_content', models.TextField(null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies_hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='companies/')),
                ('content_text', models.TextField()),
                ('Companies_hiring', models.CharField(max_length=50, null=True)),
                ('alumini_count', models.CharField(max_length=50, null=True)),
                ('placement_rate', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excellence_in_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_text', models.TextField()),
                ('category', models.CharField(choices=[('Centre Of Excellence', 'Centers OF EXcellence'), ('Research Labs', 'Researc Labs'), ('Infrastructure', 'Infrastructure')], max_length=50)),
                ('image', models.ImageField(upload_to='realtedimg/')),
            ],
        ),
        migrations.CreateModel(
            name='GlanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('student_count', models.CharField(max_length=50, null=True)),
                ('programs_count', models.CharField(max_length=50, null=True)),
                ('faculty_member', models.CharField(max_length=50, null=True)),
                ('acres_camus', models.CharField(max_length=50, null=True)),
                ('placement_rate', models.CharField(max_length=50, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='leadership/')),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsandEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('content_text', models.TextField()),
                ('category', models.CharField(choices=[('Latest News', 'Latest News'), ('Notices/Circular', 'Notices/Circular'), ('Upcoming Events', 'Upcoming Events')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('button1_text', models.CharField(max_length=50)),
                ('video_link', models.URLField()),
                ('background_color', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
