# Generated by Django 5.2.2 on 2025-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
