# Generated by Django 5.2.2 on 2025-06-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campusimg/')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campus_life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realtedimg/')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Companies_hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='companies/')),
                ('content_text', models.TextField()),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Excellence_in_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content_text', models.TextField()),
                ('image', models.ImageField(upload_to='realtedimg/')),
            ],
        ),
        migrations.CreateModel(
            name='GlanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='leadership/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsandEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('content_text', models.TextField()),
                ('category', models.CharField(choices=[('Latest News', 'Latest News'), ('Notices', 'Notices'), ('Academic Events', 'Academic Events')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Glance',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='quickaccess',
            old_name='icon_name',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='quickaccess',
            name='color',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
