# Generated by Django 5.2.3 on 2025-06-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0002_alter_excellence_in_education_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellence_in_education',
            name='category',
            field=models.CharField(choices=[('centre of excellence', 'Centers OF EXcellence'), ('Research Labs', 'Researc Labs'), ('infrastructure', 'Infrastructure')], max_length=50),
        ),
    ]
