# Generated by Django 5.2.2 on 2025-06-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0002_leadership_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='url',
        ),
    ]
