# Generated by Django 5.2.2 on 2025-06-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0003_alter_excellence_in_education_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellence_in_education',
            name='category',
            field=models.CharField(choices=[('Centre Of Excellence', 'Centers OF EXcellence'), ('Research Labs', 'Researc Labs'), ('Infrastructure', 'Infrastructure')], max_length=50),
        ),
    ]
