# Generated by Django 5.2.2 on 2025-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0006_alter_excellence_in_education_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickaccess',
            name='title',
        ),
        migrations.AddField(
            model_name='leadership',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='button1_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='excellence_in_education',
            name='category',
            field=models.CharField(choices=[('Centers OF EXcellence', 'Centre Of Excellence'), ('Research Labs', 'Researc Labs'), ('Infrastructure', 'Infrastructure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quickaccess',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quickaccess',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
