# Generated by Django 5.2.2 on 2025-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pageapp', '0018_alter_excellence_in_education_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellence_in_education',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
