# Generated by Django 5.2.2 on 2025-07-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('card_title', models.CharField(max_length=50)),
                ('card_desc', models.TextField()),
                ('background_color', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('card_subtitle', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChancellorHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChancellorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('background_color', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('card_title', models.CharField(max_length=120, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('category_icon', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSectionAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('button1_text', models.CharField(max_length=50)),
                ('button2_text', models.CharField(max_length=50)),
                ('button1_url', models.URLField()),
                ('button2_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowViceChancellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=255)),
                ('card_title', models.CharField(max_length=100, null=True)),
                ('card_subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(null=True)),
                ('card_description', models.TextField(null=True)),
                ('achievement_title', models.CharField(max_length=50, null=True)),
                ('achievement_subtitle', models.CharField(max_length=50, null=True)),
                ('achievement_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryBodySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('items_available', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('card_title', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('sub_title', models.CharField(max_length=50, null=True)),
                ('naac_grade', models.CharField(max_length=50, null=True)),
                ('compliance_rate', models.CharField(max_length=50, null=True)),
                ('transparency_index', models.CharField(max_length=50, null=True)),
                ('audit_score', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliciesHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=50, null=True)),
                ('card_desc', models.CharField(max_length=50, null=True)),
                ('icon_class', models.CharField(max_length=50, null=True)),
                ('ques', models.TextField(blank=True)),
                ('button1_text', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('card_title', models.CharField(max_length=50, null=True)),
                ('card_desc', models.TextField(null=True)),
                ('year', models.DateField(null=True)),
                ('url', models.URLField(null=True)),
                ('icon_class', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViceChancellorHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViceChancellorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
