# Generated by Django 5.2.2 on 2025-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='aboutus_gbu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about_gbu/')),
            ],
        ),
        migrations.CreateModel(
            name='aboutus_joingbu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='join_gbu/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button3_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('button3_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aboutus_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Academic_school_programs_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='facilities_infrastructure_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governance_committee_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governance_organizational_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Governance_organizatonal_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Green_eco_friendly_campus_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_resedential_life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostel_image/')),
                ('facilities', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mandatory_compliance_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mandatory_compliance_information_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(blank=True, choices=[('Academic Information', 'Academic Information'), ('Financial Disclosure', 'Financial Disclosure'), ('Faculty Information', 'Faculty Information'), ('Infrastructure Details', 'Infrastructure Details')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mandatory_compliance_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='wellnes_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Meditation_wellnes_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('button1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meditation_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Regulatory_compliance_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research_innovation_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sports_reaction_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports_Reaction_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.ManyToManyField(blank=True, to='aboutapp.sports_reaction_features')),
            ],
        ),
        migrations.CreateModel(
            name='student_life_community_highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WMeditation_ellness_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The name of the feature (e.g. Yoga)', max_length=100)),
                ('icon', models.CharField(help_text='Emoji or icon class (e.g. 🧘\u200d♂️ or fa-yoga)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Custom ordering')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUsCard',
        ),
        migrations.DeleteModel(
            name='GovernanceCard',
        ),
        migrations.DeleteModel(
            name='KnowViceChancellor',
        ),
        migrations.DeleteModel(
            name='MandatoryBodySection',
        ),
        migrations.DeleteModel(
            name='RegulatoryCompliance',
        ),
        migrations.DeleteModel(
            name='RTI',
        ),
        migrations.RemoveField(
            model_name='chancellorherosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='card_title',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='category_icon',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='governanceherosection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='herosectionaboutus',
            name='button1_text',
        ),
        migrations.RemoveField(
            model_name='herosectionaboutus',
            name='button1_url',
        ),
        migrations.RemoveField(
            model_name='herosectionaboutus',
            name='button2_text',
        ),
        migrations.RemoveField(
            model_name='herosectionaboutus',
            name='button2_url',
        ),
        migrations.RemoveField(
            model_name='mandatoryherosection',
            name='audit_score',
        ),
        migrations.RemoveField(
            model_name='mandatoryherosection',
            name='compliance_rate',
        ),
        migrations.RemoveField(
            model_name='mandatoryherosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mandatoryherosection',
            name='naac_grade',
        ),
        migrations.RemoveField(
            model_name='mandatoryherosection',
            name='transparency_index',
        ),
        migrations.RemoveField(
            model_name='policiesherosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='universitypolicy',
            name='url',
        ),
        migrations.RemoveField(
            model_name='vicechancellorherosection',
            name='description',
        ),
        migrations.AddField(
            model_name='chancellorherosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='chancellor_background/'),
        ),
        migrations.AddField(
            model_name='chancellorherosection',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chancellormessage',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chancellormessage',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chancellors_image'),
        ),
        migrations.AddField(
            model_name='governanceherosection',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectionaboutus',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectionaboutus',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mandatoryherosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesherosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesherosection',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='universitypolicy',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='universitypolicy',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vicechancellorherosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='chancellor_background/'),
        ),
        migrations.AddField(
            model_name='vicechancellorherosection',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vicechancellormessage',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vicechancellormessage',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vicechancellormessage',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vicechancellors_image'),
        ),
        migrations.AlterField(
            model_name='chancellorherosection',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chancellorherosection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chancellormessage',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chancellormessage',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chancellormessage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chancellormessage',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chancellormessage',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='governanceherosection',
            name='category',
            field=models.CharField(blank=True, choices=[('Finance Committee', 'Finance Committee'), ('Executive Council', 'Executive Council'), ('Academic Council', 'Aacademic Council')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosectionaboutus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mandatoryherosection',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mandatoryherosection',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mandatoryherosection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policiesherosection',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policiesherosection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='card_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='category',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Resarch', 'Research'), ('Student Affairs', 'Student Affairs'), ('Financial', 'Financial'), ('Admission', 'Admission')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universitypolicy',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vicechancellorherosection',
            name='background_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vicechancellorherosection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vicechancellormessage',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vicechancellormessage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vicechancellormessage',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vicechancellormessage',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governanceherosection',
            name='highlights',
            field=models.ManyToManyField(blank=True, to='aboutapp.governance_committee_highlights'),
        ),
        migrations.AddField(
            model_name='meditation_wellnes_center',
            name='features',
            field=models.ManyToManyField(blank=True, to='aboutapp.wmeditation_ellness_feature'),
        ),
    ]
