# Generated by Django 5.2.2 on 2025-06-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='JoinOurAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Join Our Alumni Banner',
                'verbose_name_plural': 'Join Our Alumni Banners',
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.IntegerField()),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('current_job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('professional_bio', models.TextField(blank=True, null=True)),
                ('available_for_job_referrals', models.BooleanField(default=False)),
                ('available_for_resume_reviews', models.BooleanField(default=False)),
                ('available_for_career_mentoring', models.BooleanField(default=False)),
                ('button1_text', models.CharField(default='Submit Registration', max_length=200)),
                ('button1_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluminiapp.branch')),
            ],
            options={
                'verbose_name': 'Alumni Profile',
                'verbose_name_plural': 'Alumni Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
