# Generated by Django 5.2.3 on 2025-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contacts/')),
                ('category', models.CharField(choices=[('vice_chancellor', 'Vice Chancellor'), ('pro_vice_chancellor', 'Pro Vice Chancellor'), ('registrar', 'Registrar'), ('deputy_registrar', 'Deputy Registrar'), ('other', 'Other')], default='other', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='contact_herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uni_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_color', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, upload_to='contact_directory/')),
                ('gradient_color', models.CharField(blank=True, help_text="Enter a CSS gradient e.g., 'linear-gradient(to right, #ff7e5f, #feb47b)'", max_length=255)),
            ],
        ),
    ]
