
# Generated by Django 5.2.3 on 2025-06-25 11:03




from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_herosection',
            name='gradient_color',
            field=models.CharField(blank=True, help_text="Enter a CSS gradient e.g., 'linear-gradient(to right, #ff7e5f, #feb47b)'", max_length=255),
        ),
    ]
