# Generated by Django 5.2.2 on 2025-07-25 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0003_academic_programs_department_board_studies_and_more'),
        ('academicapp', '0002_academic_schedule_regulatioons_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments_herosection',
        ),
        migrations.DeleteModel(
            name='deprtment_herosection_skills',
        ),
        migrations.DeleteModel(
            name='Placement_herosection_image',
        ),
        migrations.RenameField(
            model_name='department_statistics',
            old_name='label',
            new_name='iconColor',
        ),
        migrations.RenameField(
            model_name='department_statistics',
            old_name='value',
            new_name='numberText',
        ),
        migrations.RenameField(
            model_name='placement_stats',
            old_name='background_color',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='placement_stats',
            old_name='label',
            new_name='iconColor',
        ),
        migrations.RenameField(
            model_name='placement_stats',
            old_name='value',
            new_name='numberText',
        ),
        migrations.RenameField(
            model_name='school_ict_herosection',
            old_name='background_color',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='startup_stats',
            old_name='color',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='startup_stats',
            old_name='label',
            new_name='iconColor',
        ),
        migrations.RenameField(
            model_name='startup_stats',
            old_name='value',
            new_name='numberText',
        ),
        migrations.RenameField(
            model_name='stats_spaeak_for_themsleves',
            old_name='color1',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='stats_spaeak_for_themsleves',
            old_name='label',
            new_name='iconColor',
        ),
        migrations.RenameField(
            model_name='stats_spaeak_for_themsleves',
            old_name='value',
            new_name='numberText',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='faculty_profile',
            name='year_experience',
        ),
        migrations.RemoveField(
            model_name='school_ict_herosection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='school_ict_herosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='school_ict_herosection',
            name='gradient',
        ),
        migrations.AddField(
            model_name='department_statistics',
            name='key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department_statistics',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department_statistics',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department_statistics',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academicapp.facultymember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placement_stats',
            name='key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement_stats',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement_stats',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placement_stats',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recent_placement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recent_placements/'),
        ),
        migrations.AddField(
            model_name='school_ict_herosection',
            name='bgTheme',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup_stats',
            name='key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup_stats',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup_stats',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup_stats',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stats_spaeak_for_themsleves',
            name='key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats_spaeak_for_themsleves',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats_spaeak_for_themsleves',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stats_spaeak_for_themsleves',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student_clubs_activities',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
