# Generated by Django 5.2.3 on 2025-06-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0002_achievement_activity_amenity_campus_life_stats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='Student_club',
            new_name='Student',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Student_club',
        ),
    ]
