# Generated by Django 5.2.3 on 2025-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0003_rename_student_club_achievement_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name_plural': 'Student club Achieveents'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Student club Activites'},
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Hostel Amenities'},
        ),
        migrations.AlterModelOptions(
            name='ecocampusstat',
            options={'verbose_name_plural': 'eco campus_titlesection'},
        ),
        migrations.AlterModelOptions(
            name='facilityfeature',
            options={'verbose_name_plural': 'sports facility'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Food tag'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Popular, Multi-Cuisine, Study Friendly, etc.', max_length=50),
        ),
    ]
