# Generated by Django 5.2.2 on 2025-06-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0003_alter_achievement_options_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='Student',
            new_name='Student_club',
        ),
    ]
