# Generated by Django 5.2.3 on 2025-06-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0003_alter_achievement_options_alter_activity_options_and_more'),
        ('campuslifeapp', '0004_alter_achievement_options_alter_activity_options_and_more'),
    ]

    operations = [
    ]
