# Generated by Django 5.2.2 on 2025-06-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0005_rename_student_club_achievement_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='Student',
            new_name='Student_club',
        ),
    ]
