# Generated by Django 5.2.3 on 2025-06-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0004_rename_student_achievement_student_club'),
        ('campuslifeapp', '0005_merge_20250626_0752'),
    ]

    operations = [
    ]
