# Generated by Django 5.2.2 on 2025-06-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0006_rename_student_achievement_student_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='Student_club',
            new_name='club_name',
        ),
    ]
