# Generated by Django 5.2.2 on 2025-06-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0006_merge_20250626_0803'),
        ('campuslifeapp', '0007_rename_student_club_achievement_club_name'),
    ]

    operations = [
    ]
