# Generated by Django 5.2.3 on 2025-06-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuslifeapp', '0008_merge_20250626_0830'),
        ('campuslifeapp', '0008_merge_20250626_0834'),
    ]

    operations = [
    ]
