from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views

router = DefaultRouter()

# Register all your viewsets
router.register(r'research-area', views.ResearchAreaViewSet)
router.register(r'faculty-directory', views.FacultyDirectoryViewSet)
router.register(r'summary-dashboard', views.SummaryDashboardViewSet)
router.register(r'about-overview', views.AboutOverviewViewSet)
router.register(r'overview-research', views.OverviewResearchViewSet)
router.register(r'overview-quicklink', views.OverviewQuickLinkViewSet)
router.register(r'educational-qualification', views.EducationalQualificationViewSet)
router.register(r'professional-experience', views.ProfessionalExperienceQualificationViewSet)
router.register(r'teaching', views.TeachingViewSet)
router.register(r'course-code', views.CourseCodeViewSet)
router.register(r'courses-taught', views.CoursesTaughtTeachingViewSet)
router.register(r'lecture-slide', views.LectureSlideTeachingViewSet)
router.register(r'teaching-stat', views.TeachingStatViewSet)
router.register(r'administration-role', views.AdministrationRoleViewSet)
router.register(r'committee-membership', views.CommitteeMembershipAdministrationViewSet)
router.register(r'administrative-impact', views.AdministrativeImpactViewSet)
router.register(r'research-collaborator', views.ResearchCollaboratorViewSet)
router.register(r'research-project', views.ResearchProjectViewSet)
router.register(r'research-stat', views.ResearchStatViewSet)
router.register(r'research-group-stat', views.ResearchGroupOverviewStatViewSet)
router.register(r'research-group-description', views.ResearchGroupOverviewDescriptionViewSet)
router.register(r'research-category', views.ResearchCategoryViewSet)
router.register(r'research-group-overview', views.ResearchGroupOverviewViewSet)
router.register(r'research-assistant', views.ResearchAssistantViewSet)
router.register(r'publications', views.PublicationsViewSet)
router.register(r'publication-statistics', views.PublicationStatisticsViewSet)
router.register(r'patent-portfolio-stats', views.PatentPortfolioStatsViewSet)
router.register(r'patent-portfolio-description', views.PatentPortfolioDescriptionViewSet)
router.register(r'patent-application', views.PatentApplicationViewSet)
router.register(r'patent-filing-timeline', views.PatentFilingTimelineViewSet)
router.register(r'professional-certifications-status', views.ProfessionalCertificationsStatusViewSet)
router.register(r'professional-certifications-description', views.ProfessionalCertificationsDescriptionViewSet)
router.register(r'skills-certifications', views.SkillsCertificationsViewSet)
router.register(r'certification-portfolio', views.CertificationPortfolioViewSet)
router.register(r'professional-development-certifications', views.ProfessionalDevelopmentCertificationsViewSet)
router.register(r'invited-talks-stats', views.InvitedTalksStatsViewSet)
router.register(r'invited-talks-description', views.InvitedTalksDescriptionViewSet)
router.register(r'speaking-engagements', views.SpeakingEngagementsViewSet)
router.register(r'speaking-expertise', views.SpeakingExpertiseViewSet)
router.register(r'award-achievements-stats', views.AwardAchievementsStatsViewSet)
router.register(r'award-achievements-description', views.AwardAchievementsDescriptionViewSet)
router.register(r'award-recognition', views.AwardRecognitionViewSet)
router.register(r'notable-achievements-award', views.NotableAchievementsAwardViewSet)
router.register(r'awards-timeline', views.AwardsTimelineViewSet)
router.register(r'social-impact-stats', views.SocialImpactStatsViewSet)
router.register(r'social-impact-description', views.SocialImpactDescriptionViewSet)
router.register(r'community-initiative-social', views.CommunityInitiativeSocialViewSet)
router.register(r'social-impact-summary', views.SocialImpactSummaryViewSet)

urlpatterns = [
    path('', include(router.urls)),
]
